### ISSUE TITLE
MCP error -32603: Failed to generate chart: fetch failed

### ISSUE THREAD

**Issue by WindowsXP-XP** [antvis/mcp-server-chart#129]
调用 MCP 时，有时候会爆这个错，有解决方案吗
```json
{
  "jsonrpc" : "2.0",
  "id" : "06f34e6c-6",
  "error" : {
    "code" : -32603,
    "message" : "MCP error -32603: Failed to generate chart: fetch failed"
  }
}

**Comment by hustcc** [comment]
出错频率高吗？

**Comment by WindowsXP-XP** [comment]
频率还不算太高，但是如果报错，可能这段时间内的调用也差不多报错，chat 时要修改对应的对话内容才可能不报错。
如果是大模型解析数据入参的问题，希望这个报错信息能更加详细点，方便对对话中的提示词进行修改，来让大模型调用MCP时能合法入参

**Comment by WindowsXP-XP** [comment]
> 出错频率高吗？

频率还不算太高，但是如果报错，可能这段时间内的调用也差不多报错，chat 时要修改对应的对话内容才可能不报错。
如果是大模型解析数据入参的问题，希望这个报错信息能更加详细点，方便对对话中的提示词进行修改，来让大模型调用MCP时能合法入参

**Comment by jiaohuix** [comment]
我也遇到了，是在试图本地部署gpt_vis_ssr后报错的。怎么解决啊

**Comment by jiaohuix** [comment]
@WindowsXP-XP 我好像解决了，不知道能否解决你的问题。

我本地部署gpt_vis_ssr后，使用VIS_REQUEST_SERVER=http://your_host:3000/render，而不是README里面的http://your_host:3000/api/chart；直接使用http://your_host:3000或者http://your_host:3000/api/chart，mcp client调用的时候都会报错32603。

我的docker-compose.yml如下：

```
version: '3.8'

services:
  # 图表渲染服务
  gpt-vis-ssr:
    image: ghcr.io/luler/gpt_vis_ssr:latest
    ports:
      - "3000:3000" 
    volumes:
      - ./images:/app/public/images  # 持久化生成的图表图片
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - vis-network  # 加入自定义网络


  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1122:1122"  
    environment:
      - PORT=1122
      - VIS_REQUEST_SERVER=http://gpt-vis-ssr:3000/render  # 通过服务名访问
    restart: unless-stopped
    depends_on:
      - gpt-vis-ssr  # 确保 gpt-vis-ssr 先启动
    networks:
      - vis-network

# 自定义网络（确保容器间直接通信）
networks:
  vis-network:
    driver: bridge

```


先测试下渲染服务正常启动，然后再接入mcp。
```
curl -X POST http://127.0.0.1:3000/render \
  -H "Content-Type: application/json" \
  -d '{
    "type": "column",
    "data": [
        {"category": "交通", "value": 2000},
        {"category": "住宿", "value": 1200},
        {"category": "吃喝", "value": 1000},
        {"category": "门票", "value": 800},
        {"category": "其他", "value": 300}
    ],
    "title": "旅行计划费用统计",
    "axisXTitle": "费用类别",
    "axisYTitle": "金额 (元)"
  }'
```
